server.port=8080
spring.application.name=secondhand-backend

spring.datasource.url=jdbc:sqlite:secondhand.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.upload.dir=uploads/images
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB